np.random.seed()\
原型:`numpy.random.seed(num)`\
作用:生成一个list顺序固定，但是内容未知

In [8]:
import numpy as np

np.random.seed(0)
print(np.random.rand(5))#随机生成五个数
print(np.random.rand(5))
np.random.seed(0)
for i in range(10):
    print(np.random.random())##生成的数据与上面完全一致，说明生成的list相同
np.random.seed(5)
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
0.5488135039273248
0.7151893663724195
0.6027633760716439
0.5448831829968969
0.4236547993389047
0.6458941130666561
0.4375872112626925
0.8917730007820798
0.9636627605010293
0.3834415188257777
[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119]


np.random.normal()\
原型:`numpy.random.normal(loc,scale,size)`\
作用:生成一个满足参数正太分布的数组
参数|说明
 --|--
 loc|正态分布的均值
 scale|正太分布的标准差
 size|设定数组的形状

In [9]:
import numpy as np
a = np.random.normal(loc=0,scale=2,size=(2,3))
a

array([[ 2.73517105,  1.14941538, -3.77152482],
       [ 0.34185074, -0.80618662,  3.27525698]])