## IO函数
numpy可以读写磁盘上文本数据或二进制数据\
\
numpy为ndarray对象引入了一个简单的文件格式: npy\
\
npy文件用于存储重建ndarray所需数据、图形、dtype和其他信息

numpy.save()\
原型:`numpy.save(file,arr,allow_pickle=true,fix_important=True)`\
作用:将数组保存到以.npy为扩展名的文件中\
参数|说明
--|--
file|要保存的文件，扩展名为.npy,如果文件路径末尾没有.npy,该扩展名会被自动加上
arr|要保存的数组
allow_pickle|可选，布尔值，允许使用python pickles 保存对象数组，python的pickle用于在保存到磁盘文件读取之前，对对象进行序列化和反序列化。
fix_imports|可选，为了在python2中读取python3保存的数据

In [2]:
import numpy as np
x = np.array([[10,10],[2,3],[4,5]])
np.save("test/output.npy",x)

numpy.savez()\
原型:`numpy.savez(file,*arg,**kwd)`\
作用：将多个数组保存到以npz为扩展名的文件中
参数|说明
--|--
file|要保存的文件，扩展名为.npy,如果文件路径末尾没有.npy,该扩展名会被自动加上
args|要保存的数组，可以使用关键字参数为数组起一个名字，非关键字参数传递的数组会自动起名arr_0,arr_1
kwds|要保存的数组使用关键字名称

In [3]:
x = np.array([2,3,4])
y = np.array([5,6,7])
z = np.array([8,9,10])

np.savez("test/uotput.npz",x,y,sin_arr=z)

In [5]:
ret=np.load("test/uotput.npz")
print(ret)

In [7]:
print(ret["arr_0"])
print(ret["sin_arr"])

[2 3 4]
[ 8  9 10]


numpy.savetxt()\
原型:`numpy.savetxt(FILENAME,a,fmt="%d",delimiter=",")`\
---  `numpy.loadtxt(FILENAME,dtype=int,delimiter=" ")`
参数|说明
--|--
dilimiter|指定各种分隔符、针对特定列的转换函数、需要跳过的行数等

In [8]:
x = np.array([1,2,3])

np.savetxt('test/out.npy',x)

In [12]:
y = np.loadtxt("test/out.npy")
print(y)

[1. 2. 3.]


In [13]:
x = np.array([1,2.1,3])

np.savetxt("test/out2.npy",x,fmt="%d",delimiter=",")

In [15]:
y = np.loadtxt("test/out2.npy",delimiter=",")##一般用“，”,有的时候需要换行
print(y)

[1. 2. 3.]
