In [4]:
#ndim秩，即是轴的数量或维度的数量
import numpy as np
arr = np.arange(24)
print (arr)
print(arr.ndim)
arr2=arr.reshape(2,3,4)
print(arr2)
print(arr2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [6]:
#shape表示维度数，即是行数和列数
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape=(3,2)
print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [9]:
#size数组元素数量  dtype类型
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
6
int32


In [11]:
#itemsize对象中每个元素的大小，以字节为单位
arr1 = np.array([1,2,3,4,5],dtype='i1')
print(arr1)
print(arr1.itemsize)

arr2 = np.array([1,2,3,4,5],dtype='f')
print(arr2)
print(arr2.itemsize)

[1 2 3 4 5]
1
[1. 2. 3. 4. 5.]
4


In [12]:
#flags对象的内存信息
arr = np.array([1,2,3,4])
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

