## 修改数组维度

broadcast() \
用于模仿广播的对象，它返回一个对象，该对象封装了将一个数组广播到另一个数组的结果

In [20]:
import numpy as np

x = np.array([[1],[2],[4]])
y = np.array([4,5,6])
print(x)
print(y)

[[1]
 [2]
 [4]]
[4 5 6]


In [21]:
b = np.broadcast(x,y)##b是一个对象
print(b)

In [22]:
r,c = b.iters
print(r)##r迭代对象
print(c)##c迭代对象

In [23]:
for a in range(0,6):
    print(next(r),next(c))


1 4
1 5
1 6
2 4
2 5
2 6


In [29]:
b = np.broadcast(x,y)
print(b.shape)

(3, 3)


In [28]:
c = np.empty(b.shape)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
print(x+y)

[[ 5  6  7]
 [ 6  7  8]
 [ 8  9 10]]


broadcast_to() \
原型:`numpy.broadcast_to(array,shape,subok=False)` \
作用:将数组广播到新形状。它在原始数组上返回只读视图。它通常不连续。如果新形状不符合Numpy的广播规则，该函数可能会抛出ValueError
 参数|说明
 --|--
 array|待修改数组
 shape|修改后的形状

In [1]:
import numpy as np
a = np.arange(1,5).reshape(1,4)
print(a)
b = np.broadcast_to(a,(3,4))##不能将列修改得比4小或者比4大，不符合广播规则
print(b)

[[1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


expand_dims() \
原型:`numpy.squeeze(arr,axis=None)`\
作用:通过在指定位置插入新的轴来扩展数组形状
 参数|说明
 --|--
 arr|待修改数组
 axis|新轴插入的位置

In [3]:
x = np.arange(1,5).reshape((2,2))
print(x)
print(x.shape,x.ndim)

[[1 2]
 [3 4]]
(2, 2) 2


In [4]:
y = np.expand_dims(x,axis=0)##增加了一个轴，一个维度
print(y)
print(y.shape,y.ndim)

[[[1 2]
  [3 4]]]
(1, 2, 2) 3


squeeze() \
原型:`numpy.squeeze(arr,axis)`\
作用:从给定数组形状中删除一维的条目
 参数|说明
 --|--
 arr|输入数组
 axis|删除轴的位置

In [9]:
import numpy as np
x = np.arange(1,10).reshape((1,3,3))
print(x)
print(x.shape,x.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3) 3


In [10]:
y = np.squeeze(x)
print(y)
print(y.shape,y.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) 2


In [11]:
y = np.squeeze(x)
y = np.squeeze(y)##不会在继续裁剪轴
print(y)
print(y.shape,y.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3) 2


In [12]:
x = np.arange(1,121).reshape(2,3,4,5)
y = np.squeeze(x)
print(y)
print(y.shape,y.ndim)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]
(2, 3, 4, 5) 4


In [13]:
x = np.arange(1,13).reshape(1,1,3,4)
y = np.squeeze(x)##不加axis参数则会将所有维度为1的轴删除
print(y)
print(y.shape,y.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4) 2


In [14]:
x = np.arange(1,13).reshape(1,1,3,4)
y = np.squeeze(x,axis=1)##不加axis参数则会将所有维度为1的轴删除
print(y)
print(y.shape,y.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4) 3
