## 分割数组
split( )\
原型:`numpy.split(ary,indices_or_sections,axis=0)`\
作用:函数沿特定的轴将数组分割为子数组
 参数|说明
 --|--
 ary|被分割的数组
 indices_or_sections|是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）

In [ ]:
import numpy as np

x = np.arange(12)
print(x)

a = np.split(x,3)#必须可以平均切分
print(a)

b = np.split(x , [2,5,6])#下标切分从下标2切一个，下标为5切一个
print(b[1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[2 3 4]


: 

In [10]:
x = np.arange(12).reshape(3,4)
print(x)

print("\n")

a = np.split(x,3,axis=0)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


: 