In [2]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[1]

1

In [4]:
s = slice(2,7,1)#slice(start,stop(取不到),step（默认为1)
arr[s]

array([2, 3, 4, 5, 6])

In [5]:
#another way:   start:stop:step
arr[2:7:1]

array([2, 3, 4, 5, 6])

In [6]:

arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#多维数组仍然可以用上述方法
arr =np.arange(15)
arr.shape=(5,3)
print(arr)
arr2=arr[2][1]
print(arr2,type(arr2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
7 <class 'numpy.ndarray'>


In [10]:
arr =np.arange(15)
arr.shape=(5,3)
print(arr)
print("\n")
arr2=arr[2:]
print(arr2,type(arr2))
print(arr2.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]] <class 'numpy.ndarray'>
(3, 3)


In [1]:
#...取值 表示所有
import numpy as np
arr =np.arange(15)
arr.shape=(5,3)
print(arr)
print("\n")
print(arr[...,1])#取一列
print("\n")
print(arr[1,...])#取一行
print("\n")
print(arr[1:3,...])#取从1到3行，但不包括第3行
print("\n")
print(arr[...,1:])#取从1列到所有列

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[ 1  4  7 10 13]


[3 4 5]


[[3 4 5]
 [6 7 8]]


[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]]
