In [2]:
import numpy as np
dt=np.dtype(np.int32)
print(dt)
print(type(dt))

int32
<class 'numpy.dtype[int32]'>


In [1]:
a = list([1,2,3])
a

[1, 2, 3]

In [4]:
#一维数组
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [1]:
#元素类型要相同
import numpy as np
arr=np.array([1,2.3,4,5])
arr

array([1. , 2.3, 4. , 5. ])

In [5]:
#多维数组
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#参数ndmin最小维度
arr = np.array([1,2,3,4,5,6,7,8,9,0],ndmin=2) #nmin 创建数组时，至少保证有 n 个维度
arr
#打印出的arr数组是只有一个元素的二维数组

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [5]:
#参数dtype数据类型
arr = np.array([1,2,3,4,5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
#结构化数据类型
import numpy as np
student=np.dtype([("name","S20"),("age","i4"),("mark","f4")])## "S20"表示字符串，string of 20 最长20个字符；"i4" int of 4 bytes 表示4字节整数；"f4"表示4字节浮点数
arr = np.array([("sunck",18,99.999),("kaige",19,98.99)],dtype=student)
arr

array([(b'sunck', 18, 99.999), (b'kaige', 19, 98.99 )],
      dtype=[('name', 'S20'), ('age', '<i4'), ('mark', '<f4')])

In [3]:
arr=np.asarray([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr=np.asarray((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [7]:
arr=np.asarray([(1,2,3),(4,5)])
arr

d:\Anconda\envs\Paddle_tutorial\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([(1, 2, 3), (4, 5)], dtype=object)

In [8]:
arr=np.asarray([1,2,3,4,5],dtype="f")
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [9]:
#empty函数 （创建的数组 数组元素是不确定的）
import numpy as np
arr = np.empty([3,2],dtype=int)
arr

array([[2011666304,        518],
       [         0,          0],
       [    131074,  538976266]])

In [11]:
#zero函数（创建指定大小的数组 数组元素以0填充）
arr = np.zeros(5,dtype=int)
arr

array([0, 0, 0, 0, 0])

In [12]:
arr = np.zeros([5,2],dtype=int)
arr,

(array([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]),)

In [13]:
arr=np.zeros([2,2],dtype=[('x','i4'),('y','f')])
arr

array([[(0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.)]], dtype=[('x', '<i4'), ('y', '<f4')])

In [15]:
#ones函数（以1来填充）
arr = np.ones(5,dtype=int)
arr

array([1, 1, 1, 1, 1])

In [1]:
#full函数，以指定内容来填充
import numpy as np
arr = np.full(5,fill_value=1024)
arr

array([1024, 1024, 1024, 1024, 1024])

In [4]:
#eye函数用来设对角线为1其它位置为0的矩阵
arr = np.eye(10,dtype=int)
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [7]:
#arange函数 根据start与stop指定的范围以及step设定的步长，生成一个ndarray数组
arr = np.arange(1,11,1)#(start,stop(拿不到),step)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#frombuffer函数  用于实现动态数组，接受buffer输入参数，以流的形式读入转化成ndarray对象
import numpy as np
x=b'show show way'#attention:buffer是字符串时，py3默认str是Unicode类型，所以要转成bytestring在原str前加上b
arr = np.frombuffer(x,dtype='S1',count=5,offset=2)
arr

array([b'o', b'w', b' ', b's', b'h'], dtype='|S1')

In [6]:
x=[1,2,3,4,5]
z = iter(x)#将x变成可迭代对象
print(z)
print (type(z))
arr = np.fromiter(z,dtype='f')
arr

<class 'list_iterator'>


array([1., 2., 3., 4., 5.], dtype=float32)

In [3]:
#linspace函数 创建一个等差数列
arr = np.linspace(1,10,num=5,endpoint=True,dtype=int)# endpoint是否包含最后一个数
arr

array([ 1,  3,  5,  7, 10])

In [13]:
#logspace函数 创建一个等比数列
arr = np.logspace(1,10,num=10,endpoint=True,dtype=int,base=2)
arr

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [10]:
#random.rand() 生成[0,1)的随机数
x=np.random.rand()
x

0.7529323205280497

In [13]:
#生成有三个元素的一维数组
x=np.random.rand(3)
x

array([0.79660066, 0.19503506, 0.41704652])

In [19]:
#生成一个二维数组
x=np.random.rand(3,3)
x

array([[0.72072614, 0.67055344, 0.08855458],
       [0.49166739, 0.32859319, 0.47029066],
       [0.91800909, 0.21709179, 0.76066114]])

In [23]:
#random.randint() 生成随机数
arr = np.random.randint(0,2,5)
arr

array([0, 0, 1, 0, 1])

In [30]:
#random.randn()  返回一个或者一组样本，具有标准正态分布
arr = np.random.randn()
arr

-1.150968498844611

In [31]:
arr = np.random.randn(2,4,3)
arr

array([[[ 1.47988747, -0.16335383, -1.91407182],
        [-0.01272791, -1.13767903, -1.34157113],
        [ 0.67047278,  0.09496792, -0.13869174],
        [-0.94511236, -0.60904191,  0.96947203]],

       [[ 0.76303128, -0.76775804, -1.20404645],
        [ 0.48091324, -0.18271589, -0.39600092],
        [ 1.10882327,  1.85766694,  0.69086452],
        [-1.8512842 , -0.5957758 ,  0.43161687]]])

In [32]:
#rand.normal()函数 生成高斯分布的概率密度随机数
arr =np.random.normal (loc=1,scale=2,size=5)
arr

array([-1.57003276,  1.48350459,  0.15097136,  3.87661538, -0.87168024])