
形状相同，如果a.shape==b.shape，那么a+b的结果就是数组对应位相加

In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a.shape)
print(b.shape)
print(a+b)

(4,)
(4,)
[3 5 7 9]


广播 如果数组形状不兼容，那么就会进行数组广播

In [2]:
import numpy as np
a = np.array([[0,0,0],
              [10,10000,10],
              [20,2220,20]
            
])
b = np.array([1,1,1]).reshape(1,3)
c = a+b
print(c)
print(a.ndim,b.ndim,c.ndim)
print(a.shape,b.shape,c.shape)

[[    1     1     1]
 [   11 10001    11]
 [   21  2221    21]]
2 2 2
(3, 3) (1, 3) (3, 3)


广播的规则
1.让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加1补齐
2.输出数组的形状是输入数组形状的各个维度上的最大值
3.如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为1时，这个数组能够用来计算，否则出错
4.当输入数组的某个维度的长度为1时，沿着此维度运算时都用此维度上的第一组值