## 排序函数

种类|速度|最坏情况|工作空间|稳定性
--|--|--|--|--
'quicksort'(快速排序)|1|O(n^2)|0|否
'mergesort'(归并排序)|2|O(n*log(n))|~n/2|是
'heapsort'(堆排序)|3|O(n*log(n))|0|否

sort()\
原型：`sort(a,axis,kind,order)`\
功能：返回输入数组的排序副本
参数|说明
--|--
a|要排序的数组
axis|沿着它展开的数组，如果没有数组会被展开，沿着最后的轴排序，
kind|排序算法，默认为'quicksort'
order|如果数组包含字段，则是要排序的字段

In [2]:
import numpy as np

x = np.random.randint(1,11,12).reshape(3,4)
print("x数组:")

print(x)



x数组:
[[ 4  1  4  3]
 [ 2  2 10  5]
 [ 5  8  5  4]]


In [6]:
a = np.sort(x)
print(a)
print("\n")
b = np.sort(x,axis=0)
print(b)
print("\n")
c = np.sort(x,axis=1)
print(c)

[[ 1  3  4  4]
 [ 2  2  5 10]
 [ 4  5  5  8]]


[[ 2  1  4  3]
 [ 4  2  5  4]
 [ 5  8 10  5]]


[[ 1  3  4  4]
 [ 2  2  5 10]
 [ 4  5  5  8]]


In [10]:
dt = np.dtype([("name","S10"),("age",int)])

y = np.array([("Liudh",34),("zhangxueyou",23),("renxianqi",40),("xiaogang",30)],dtype=dt)
print(y)

[(b'Liudh', 34) (b'zhangxueyo', 23) (b'renxianqi', 40) (b'xiaogang', 30)]


In [11]:
c = np.sort(y,order="age")##根据字段
print(c)

[(b'zhangxueyo', 23) (b'xiaogang', 30) (b'Liudh', 34) (b'renxianqi', 40)]


argsort() \
作用：对输入数组，沿着给定轴执行间接排序，并使用指定排序类型返回数据的索引数组。这个索引数组用于构造排序后的数组


In [3]:
import numpy as np
x = np.array([3,1,2])
print(x)
print("\n")

a = np.argsort(x)
print(a)
print("\n")

b = x[a]
print(b)

for index in a:
    print(x[index])

[3 1 2]


[1 2 0]


[1 2 3]
1
2
3


lexsort()\
作用:使用键序列执行间接排序。键可以看作是电子表格中的一列。该函数返回一个索引数组，使用它可以获得排序数据。

In [17]:
import numpy as np

nm = ('4','1','2','3')
dv = ('1','2','3','4')

a = np.lexsort((dv,nm))
print(a)

[1 2 3 0]


In [18]:
print([nm[i] + "," + dv[i] for i in a])

['1,2', '2,3', '3,4', '4,1']


sort_complex()
作用:对复数先排实部再排复部

In [20]:
x = np.array([5,3,6,2,1])
print(x)

print("\n")
print(np.sort_complex(x))

[5 3 6 2 1]


[1.+0.j 2.+0.j 3.+0.j 5.+0.j 6.+0.j]


In [22]:
y = np.array([1+2j,2-1j,3-2j,3-3j,3+5j])
print(y)

print('\n')

print(np.sort_complex(y))

[1.+2.j 2.-1.j 3.-2.j 3.-3.j 3.+5.j]


[1.+2.j 2.-1.j 3.-3.j 3.-2.j 3.+5.j]


partition(a,kth[axis,kind,order]) \
作用:指定一个数，对数组进行分区

In [26]:
import numpy as np
x = np.array([3,2,2,0,6,1,2,4,5])
print(x)
print("\n")

print(np.partition(x,3))##比3小的放在3的前面，比3大的放在3的后面

print("\n")

print(np.partition(x,(3,4)))##对区间进行划分

[3 2 2 0 6 1 2 4 5]


[2 0 1 2 3 2 4 5 6]


[2 0 1 2 2 3 4 5 6]


argpartition(a,kth[axis,kind,order])\
作用:可以通过关键字kind指定算法沿着指定轴对数组进行分区

In [1]:
import numpy as np

y = np.array([46,57,23,39,1,10,0,120])
print(y)

[ 46  57  23  39   1  10   0 120]


In [4]:
print(np.argpartition(y,2))##第二小的排序

print(np.argpartition(y,-2))##第二大的排序

a = np.argpartition(y,2)
b = np.argpartition(y,-2)
print('\n')
for i in a:
    print(y[i])
print('\n')
for i in b:
    print(y[i])

[6 4 5 3 1 2 0 7]
[5 3 2 6 4 0 1 7]


0
1
10
39
57
23
46
120


10
39
23
0
1
46
57
120


In [5]:
print(y[np.argpartition(y,2)])##第二小的排序
print(y[np.argpartition(y,2)][2])##取出第二小的值
print(y[np.argpartition(y,-2)])##第二大的排序
print(y[np.argpartition(y,-2)][-2])##取出第二大的值

[  0   1  10  39  57  23  46 120]
10
[ 10  39  23   0   1  46  57 120]
57
