## 搜索函数

max(),min()\
作用:沿给定轴返回最大和最小值

In [1]:
import numpy as np
x = np.array([[30,40,70],[80,30,10],[50,90,60]])

print(x)

[[30 40 70]
 [80 30 10]
 [50 90 60]]


In [2]:
print(x.flatten())##数组展开

[30 40 70 80 30 10 50 90 60]


In [4]:
print(np.max(x,axis=0))
print(np.max(x,axis=1))

[80 90 70]
[70 80 90]


argmax(),argmin()\
作用：返回最大最小值的索引

In [5]:
print(np.argmax(x))

7


In [6]:
print(np.argmax(x,axis=0))
print(np.argmax(x,axis=1))

[1 2 0]
[2 0 1]


nonzero()\
作用：返回数组中非零数组的索引

In [8]:
x = np.array([[0,40,70],[80,30,10],[50,90,60]])

print(x)

[[ 0 40 70]
 [80 30 10]
 [50 90 60]]


In [9]:
print(np.nonzero(x))##返回两组索引,分别对应行和列

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


where()\
作用:返回数组输入数组中满足给定元素的索引

In [14]:
x = np.array([[0,40,70],[80,20,10],[50,90,60]])
print(x)

[[ 0 40 70]
 [80 20 10]
 [50 90 60]]


In [15]:
y = np.where(x>30)
print(y)
print('\n')


(array([0, 0, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 0, 1, 2], dtype=int64))




In [16]:
print(x[y])

[40 70 80 50 90 60]


extract()\
作用:根据某个条件从数组中抽取元素，返回满条件的元素