## 数学函数

In [2]:
import numpy as np

a = np.array([0,30,60,90])

sin = np.sin(a*np.pi/180)
cos = np.cos(a*np.pi/180)
tan = np.tan(a*np.pi/180)
print(sin)
print(cos)
print(tan)

[0.        0.5       0.8660254 1.       ] [1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17] [0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]


反三角函数arcsin(),arccos(),arctan()

around( )\
原型:`numpy.around(a,decimals=0)`\
作用:返回指定数字的四舍五入值
参数|说明
 --|--
 a|数组
 decimals|舍入的小数位数。默认为0。如果为负，整数将四舍五入到小数点左侧的位置

In [3]:
x = np.array([3.125,456.325,5471.12,520])
print(np.around(x))
print(np.around(x,decimals=1))
print(np.around(x,decimals=-1))

[3.000e+00 4.560e+02 5.471e+03 5.200e+02]
[3.1000e+00 4.5630e+02 5.4711e+03 5.2000e+02]
[   0.  460. 5470.  520.]


floor()和ceil()函数