resize()\
原型:`numpy.resize(arr.shape)`\
作用:返回指定大小的新数组
参数|说明
--|--
arr|要修改大小的数组
shape|返回数组的新形状


In [6]:
import numpy as np
x = np.arange(6).reshape(2,3)
print(x)
print("\n")
y = np.resize(x,(3,2))
print(y)
print("\n")

z = np.resize(x,(4,3))
print(z)
print(z.shape)

[[0 1 2]
 [3 4 5]]


[[0 1]
 [2 3]
 [4 5]]


[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
(4, 3)


append()\
原型:`numpy.append(arr,value)`\
作用: 在数组末尾添加值\
     追加操作会分配整个数组，并把原来的数组复制到新的数组中\
     输入数组的维度必须匹配否则则生成ValueError
参数|说明
--|--
arr|输入数组
values|要向arr添加的值,需要和arr形状相同(除了要添加的轴)
axis|默认为None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1时。为0的时候（列数要相同）。当axis为1时，数组加在右边（行数要相同）




In [10]:
x = np.arange(6).reshape(2,3)
print(x)
print("\n")

a = np.append(x,[7,8,9])##当axis无定义时，是横向加成，返回总是为一维数组！
print(a)
print(a.shape)
print("\n")

b = np.append(x,[[7,8,9]], axis=0)##为0的时候（列数要相同）
print(b)
print(b.shape)
print("\n")

c = np.append(x,[[7,8,9],[10,11,12]],axis=1)##当axis为1时，数组加在右边（行数要相同）
print(c)
print(c.shape)

[[0 1 2]
 [3 4 5]]


[0 1 2 3 4 5 7 8 9]
(9,)


[[0 1 2]
 [3 4 5]
 [7 8 9]]
(3, 3)


[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
(2, 6)


insert()\
原型:`numpy.insert(arr,obj,values,axis)`\
作用:在给定索引之前，沿给定轴在数组中插入值\
注意:如果值的类型转换为要插入，则它与输入数组不同。插入没有原地的，函数会返回一个新的数组。此外，如果未提供轴，则输入数组会被展开

参数|说明
--|--
arr|输入数组
obj|在其前插入值的索引
values|要插入的值
axis|沿着它要插入的轴，如果未提供，则输入数组会被展开

In [11]:
x = np.arange(6).reshape(3,2)
print(x)
print("\n")


[[0 1]
 [2 3]
 [4 5]]




In [12]:
a = np.insert(x,3,[11,12])##向下标3处插入[11,12],并将其展开成一维数组
print(a)

[ 0  1  2 11 12  3  4  5]


In [14]:
b = np.insert(x,3,[11,12],axis=0)
print(b)

print("\n")

b = np.insert(x,3,[11],axis=0)##只有一个数则会进行广播
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [11 12]]


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [11 11]]


In [18]:
c = np.insert(x,1,11,axis=1)##向列方向添加数组
print(c)

print("\n")

c = np.insert(x,1,[[11],[12]],axis=1)
print(c)

[[ 0 11  1]
 [ 2 11  3]
 [ 4 11  5]]


[[ 0 11 12  1]
 [ 2 11 12  3]
 [ 4 11 12  5]]


delete()\
原型:`numpy.delete(arr,obj,axis)`\
作用:返回输入数组中删除指定子数组的新数组。与insert()函数的情况一样，如果未提供轴参数，则输入数组会被展开。
参数|说明
--|--
arr|输入数组
obj|可以被切片，整数或者整数数组，表明要从输入数组删除的子数组
axis|沿着它要插入的轴，如果未提供，则输入数组会被展开

In [32]:
x = np.arange(2,14).reshape((3,4))
print(x)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [33]:
a = np.delete(x,4)##沿着它要插入的轴，如果未提供，则输入数组会被展开
print(a)

[ 2  3  4  5  7  8  9 10 11 12 13]


In [34]:
x ##原数组依然没改变

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [37]:
b = np.delete(x,1,axis=1)##将下标为1的列全部删除
print(b)

[[ 2  4  5]
 [ 6  8  9]
 [10 12 13]]


In [38]:
c = np.delete(x,1,axis=0)##将下标为1的行全部删除
print(c)

[[ 2  3  4  5]
 [10 11 12 13]]


: 