## 算数函数

add(),subtract(),multiply(),divide()\
作用:加减乘除

In [1]:
import numpy as np

x = np.arange(9,dtype='f').reshape(3,3)
print("x数组：")
print(x)
print("\n")

y = np.array([10,10,10])
print("y数组：")
print(y)
print("\n")

print(np.add(x,y))
print("--------------------")
print(x+y)


x数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


y数组：
[10 10 10]


[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
--------------------
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [2]:
import numpy as np

x = np.arange(9,dtype='f').reshape(3,3)
print("x数组：")
print(x)
print("\n")

y = np.array([10,10,10])
print("y数组：")
print(y)
print("\n")

print(np.subtract(x,y))
print("--------------------")
print(x-y)

x数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


y数组：
[10 10 10]


[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
--------------------
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


In [3]:
import numpy as np

x = np.arange(9,dtype='f').reshape(3,3)
print("x数组：")
print(x)
print("\n")

y = np.array([10,10,10])
print("y数组：")
print(y)
print("\n")

print(np.multiply(x,y))
print("--------------------")
print(x*y)

x数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


y数组：
[10 10 10]


[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
--------------------
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [5]:
import numpy as np

x = np.arange(9,dtype='f').reshape(3,3)
print("x数组：")
print(x)
print("\n")

y = np.array([10,10,10])
print("y数组：")
print(y)
print("\n")

print(np.divide(x,y))
print("--------------------")
print(x/y)

x数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


y数组：
[10 10 10]


[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
--------------------
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


reciprocal()\
作用:返回参数逐个元素的倒数

In [6]:
x = np.array([0.25,0.5,1,100,0.333])
print(np.reciprocal(x))

[4.       2.       1.       0.01     3.003003]


power()\
作用:将第一个输入数组中的元素作为底数，计算它与第二个输入数组中相应元素的幂

In [7]:
x = np.array([2,3,4])
y = np.array([1,2,3])
print(np.power(x,y))

[ 2  9 64]


mod(),remainder()\
作用:计算输入数组中相应元素的相除后的余数

In [8]:
x = np.array([10,10,10])
y = np.array([2,3,4])
print(np.mod(x,y))
print(np.remainder(x,y))

[0 1 2]
[0 1 2]
