## 统计函数

ptp()\
作用:计算数组中元素的最大值与最小值的差

In [1]:
import numpy as np
x = np.random.randint(1,11,9).reshape((3,3))##随机生成一个数组，其中元素在1——11之间，取9个元素
print(x)

[[2 2 7]
 [2 6 9]
 [5 5 6]]


In [2]:
print(np.amax(x,0))##竖轴
print(np.amax(x,1))##横轴

[5 6 9]
[7 9 6]


In [3]:
print(np.amin(x,0))
print(np.amin(x,1))

[2 2 6]
[2 2 5]


In [5]:
print(np.ptp(x,0))
print(np.ptp(x,1))
print(np.ptp(x))

[3 4 3]
[5 7 1]
7


percentile()\
原型:`numpy.percentile(a,p,axis)`\
作用:百分位数是统计中使用的度量，表示小于这个值的观察值的百分比
 参数|说明
 --|--
 a|输入数组
 p|要计算的百分位数,在0 ~ 100之间
 axis|沿着它计算百分位数的轴

 说明：\
 第 p 个百分位数是这样一个值，它使得至少有 p% 的数据项小于或等于这个值，且
至少有 (100-p)% 的数据项大于或等于这个值.\
高等院校的入学考试成绩经常以百分位数的形式报告。比如，假设某个考生在入学考
试中的语文部分的原始分数为 54 分。相对于参加同一考试的其他学生来说，他的成
绩如何并不容易知道。但是如果原始分数54分恰好对应的是第70百分位数，我们就
能知道大约70%的学生的考分比他低，而约30%的学生考分比他高。这里的 p=70

In [9]:
import numpy as np
x = np.array([[10,7,4],[3,2,1]])
print(x)

[[10  7  4]
 [ 3  2  1]]


In [10]:
print(np.percentile(x,50))
print(np.percentile(x,50,axis=0))##竖轴
print(np.percentile(x,50,axis=1))##横轴

3.5
[6.5 4.5 2.5]
[7. 2.]


median()\
作用:算数组中元素的中位数（中值）

In [1]:
import numpy as np

x = np.array([[30,65,70],[80,95,10],[50,90,60]])
print(x)

[[30 65 70]
 [80 95 10]
 [50 90 60]]


In [3]:
print(np.median(x))
print(np.median(x,axis=0))
print(np.median(x,axis=1))

65.0
[50. 90. 60.]
[65. 80. 60.]


mean()\
作用：算数组中的平均值

In [4]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


average()\
作用：根据在另一个数组中给出的各自权重计算数组中元素的加权平均值，可以接受一个轴参数。如果没有指定轴，则数组将会展开

In [6]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [8]:
print(np.average(x))

2.5


In [9]:
wts = np.array([4,3,2,1])
print(np.average(x,weights=wts))

2.0


In [10]:
x = np.array([0,1,2,3,4,5]).reshape((3,2))
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [11]:
wts = np.array([3,5])
print(np.average(x,axis=1,weights=wts))##横轴

[0.625 2.625 4.625]


标准差\
公式:std = sqrt(mean(x-x.mean())**2)


In [12]:
x = np.array([1,2,3,4])
print(np.std(x))

1.118033988749895


方差

In [13]:
print(np.var([1,2,3,4]))



1.25
