## 翻转数组


transpose() \
原型：`numpy.transpose(a,axes=None)` \
作用：对换数组维度 \
注意：会修改原始数组 \
参数|说明
--|--
a|要操作的元素
axes|整数列表，对应维度，通常所有维度都会对换


In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a)
print("\n")

b = np.transpose(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [2]:
a = np.arange(12).reshape(3,4)
print(a)
print("\n")

b=a.T
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


rollaxis() \
原型：`numpy.rollaxis(a,aixs,start=0)`\
作用：向后滚动到一个特定的位置 \
参数|说明
--|--
a|要操作的元素
aixs|向后滚动的轴，其它轴不会改变
start| 默认为0，表示完整的滚动，会滚动到特定的位置

In [4]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print("\n")

b = np.rollaxis(a,1)#只有0维度和1维度
print(b)
print("\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]




In [6]:
a = np.arange(12).reshape(3,2,2)
print(a)
print(a.shape)
print("\n")

b = np.rollaxis(a,2)
print(b)
print(b.shape)
print("\n")

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(3, 2, 2)


[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 1  3]
  [ 5  7]
  [ 9 11]]]
(2, 3, 2)




In [9]:
a = np.arange(48).reshape(2,2,3,4)
print(a)
print(a.shape)
print("\n")

b = np.rollaxis(a,3,start=1)
print(b)
print(b.shape)
print("\n")

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
(2, 2, 3, 4)


[[[[ 0  4  8]
   [12 16 20]]

  [[ 1  5  9]
   [13 17 21]]

  [[ 2  6 10]
   [14 18 22]]

  [[ 3  7 11]
   [15 19 23]]]


 [[[24 28 32]
   [36 40 44]]

  [[25 29 33]
   [37 41 45]]

  [[26 30 34]
   [38 42 46]]

  [[27 31 35]
   [39 43 47]]]]
(2, 4, 2, 3)




swapaxes() \
原型：`numpy.swapaxes(a,axis1,axis2)` \
作用：交换数组的两个轴 
参数|说明
--|--
a|要操作的元素
aixs1|对应第一个轴的整数
start|对应第二个轴的整数

In [11]:
a = np.arange(24).reshape(2,3,4)
print(a)
print(a.shape)
print("\n")

b = np.swapaxes(a,2,0)
print(b)
print(b.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)
