concatenate()\
原型:`numpy.concatenate`\
作用:用于沿指轴连接相同形状的两个或者多个数组
参数|说明
 --|--
 a1,a2,...|相同类型的数组
 axis|沿着它连接数组的轴,默认为0

In [5]:
import numpy as np
x = np.arange(4).reshape((2,2))
print(x)
print("\n")
y=np.arange(4,8).reshape((2,2))
print(y)
print("\n")
print(np.concatenate((x,y)))
print("\n")
print(np.concatenate((x,y),axis=1))

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


[[0 1]
 [2 3]
 [4 5]
 [6 7]]


[[0 1 4 5]
 [2 3 6 7]]


stack()\
原型:`numpy.stack(arrays,axis)`\
作用:用于沿新轴连接数组序列
参数|说明
 --|--
 array|相同形状的数组序列
 axis|数组中的轴，输入数组沿着它来堆叠

In [6]:
x = np.arange(4).reshape((2,2))
print(x)
print("\n")
y=np.arange(4,8).reshape((2,2))
print(y)
print("\n")
a = np.stack((x,y),0)##
print(a)
print(a.shape,a.ndim)
print("\n")
b = np.stack((x,y),1)
print(b)
print(b.shape,b.ndim)

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2) 3


[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
(2, 2, 2) 3


hstack()\
stack()的变体,横向堆叠


In [7]:
x = np.arange(4).reshape((2,2))
print(x)
print("\n")
y=np.arange(4,8).reshape((2,2))
print(y)
print("\n")
a = np.hstack((x,y))
print(a)
print(a.shape,a.ndim)

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


[[0 1 4 5]
 [2 3 6 7]]
(2, 4) 2


In [8]:
x = np.arange(4).reshape((2,2))
print(x)
print("\n")
y=np.arange(4,8).reshape((2,2))
print(y)
print("\n")
a = np.vstack((x,y))##vstack()竖直堆叠
print(a)
print(a.shape,a.ndim)

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2) 2
