In [3]:
import numpy as np 
a = np.arange(12)
print(a,end="\n")
a = a.reshape(4,3)
print(a,end="\n")
for x in np.nditer(a):#nditer迭代器
    print(x,end=" ,")
print(" ")


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0 ,1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 , 


## a.T矩阵转置 遍历顺序
如果对转置改变它的数据存储方式，那么就会改变它的遍历顺序

In [8]:
import numpy as np 
a = np.arange(12)
a = a.reshape(3,4)
print(a,end="\n")
for x in np.nditer(a):#nditer迭代器
    print(x,end=" ,")
print(" ")

print(a.T)
print("\n")
for x in np.nditer(a.T):
    print(x,end=",")
print("\n")

b = a.T.copy(order="C")##这个新的数组存储的数据格式就是按转置之后的数据格式 column
print(b)
print("\n")
for x in np.nditer(b):
    print(x,end=",")
print("\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 ,1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 , 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


0,1,2,3,4,5,6,7,8,9,10,11,

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


0,4,8,1,5,9,2,6,10,3,7,11,



## 控制遍历的顺序
改变参数order="C"进行 行优先存储
       order="F"     列

In [3]:
c = a.T.copy(order="C")
for x in np.nditer(c):
    print(x,end=",")
print("\n")

0,4,8,1,5,9,2,6,10,3,7,11,



In [4]:
c = a.T.copy(order="F")
for x in np.nditer(c):
    print(x,end=",")
print("\n")

0,1,2,3,4,5,6,7,8,9,10,11,



In [9]:
import numpy as np 
a = np.arange(12)
a = a.reshape(3,4)
print(a,end="\n")
for x in np.nditer(a,order="F",op_flags=["readwrite"]):#op_flags修改只读参数，设为可以写入
    x[...]=x**2 ##对 x 进行“原地（in-place）修改”，将 x 中的每一个元素乘以 2，等价于x[:] = x*2
print(" ")
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [6]:
import numpy as np 
a = np.arange(12)
a = a.reshape(3,4)
print(a,end="\n")
for x in np.nditer(a,flags=["external_loop"],order="F"):#flags将一个零维数组以一维数组的形式输出
    print(x,end=",")
print(" ")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8],[1 5 9],[ 2  6 10],[ 3  7 11], 


## 广播遍历

In [9]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [10]:
for x, y in np.nditer([a,b]):##必须可以进行广播
    print("%d:%d"%(x,y),end=",")
print("")

0:1,1:2,2:3,3:4,4:1,5:2,6:3,7:4,8:1,9:2,10:3,11:4,
