整数数组索引

In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 我想取 (0,0) (1,2) (2,1)的元素
print(arr[0,0],arr[1,2],arr[2,1])
arr1 = np.array([arr[0,0],arr[1,2],arr[2,1]])
print(arr1)
print("\n")
print(arr[[0,1,2],[0,2,1]])


1 6 8
[1 6 8]


[1 6 8]


rows = [[0,0],[3,3]]
columns = [[0,2],[0,2]]

In [8]:
#取四个角的元素
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])#(0,0)(0,2)(3,0)(3,2)
print(arr)
# print("\n")
rows = [[0,0],[3,3]]
columns = [[0,2],[0,2]]
print(arr[rows,columns])#一个二维数组
# print("\n")
# rows=[0,0,3,3]
# columns=[0,2,0,2]
# print(arr[rows,columns]),

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  3]
 [10 12]]


借助切片：或...与索引数组组合

In [12]:
arr = np.arange(12)
print(arr[:])

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print("\n")
print(arr[1:3,1:3])#a[ , ]前面的空表示行，后面的空表示列
print("\n")
print(arr[1:3,[1,2]])
print("\n")
print(arr[...,1:])
print("\n")


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[5 6]
 [8 9]]


[[5 6]
 [8 9]]


[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]




布尔索引 布尔数

1


In [18]:
import numpy as np
find_number = 5
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr[arr==find_number])

[5]


In [5]:
arr = np.array([np.nan,1,2,np.nan,3,5,6])
print(arr)
print(arr[~np.isnan(arr)])#np.isnan判断是否为NaN数字，是则输出其，“~”表示取其补集


[nan  1.  2. nan  3.  5.  6.]
[1. 2. 3. 5. 6.]
