In [1]:
import torch

创建一个随机值，矩阵

In [2]:
x = torch.rand(5,3)
x

tensor([[0.1621, 0.5730, 0.3271],
        [0.2298, 0.6879, 0.8453],
        [0.3842, 0.2758, 0.4282],
        [0.5359, 0.1967, 0.9225],
        [0.0010, 0.1847, 0.7280]])

初始化一个全零矩阵

In [ ]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

直接传入数据

In [4]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [5]:
x = x.new_ones(5,3,dtype=torch.double)

x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.0095,  0.3296,  1.9963],
        [ 0.5947, -0.4099, -0.5642],
        [ 1.8584, -1.8780,  0.7267],
        [-0.9330, -0.9796,  1.7538],
        [-1.0268, -0.5457, -1.2800]])

展示矩阵大小

In [6]:
x.size()

torch.Size([5, 3])

### 基本计算方法

In [7]:
y = torch.randn(5,3)
x + y

tensor([[ 0.9489, -0.7044,  1.4983],
        [ 0.1912, -1.5342, -1.3505],
        [ 1.6518, -1.7407, -0.3994],
        [-0.4150, -2.1845,  2.0073],
        [-2.4053, -0.0408, -0.7214]])

In [8]:
torch.add(x,y)# 一样是加法

tensor([[ 0.9489, -0.7044,  1.4983],
        [ 0.1912, -1.5342, -1.3505],
        [ 1.6518, -1.7407, -0.3994],
        [-0.4150, -2.1845,  2.0073],
        [-2.4053, -0.0408, -0.7214]])

### 索引

tensor 张量

In [9]:
x[:,1]

tensor([ 0.3296, -0.4099, -1.8780, -0.9796, -0.5457])

### view操作可以改变矩阵维度

In [1]:
import torch

d:\Anconda\envs\Paddle_tutorial\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [10]:
x = torch.randn(4,4)

y = x.view(16)

z = x.view(-1,8) ## -1是自动计算的意思

print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 与Numpy协同操作

In [11]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)