### BCELoss

$loss(o,t) = -\frac{\sum_{i}{(t[i]\times\log{o[i]})+(1-t[i])\times\log{(1-o[i])}}}{n}$

In [2]:
import torch 
from torch import autograd

input = autograd.Variable(torch.tensor([[1.9072, 1.1079, 1.4906],
                                        [-0.6584, -0.0512, 0.7608],
                                        [-0.0614, 0.6583, 0.1095]]),requires_grad = True)

print(input)

tensor([[ 1.9072,  1.1079,  1.4906],
        [-0.6584, -0.0512,  0.7608],
        [-0.0614,  0.6583,  0.1095]], requires_grad=True)


In [3]:
from torch import nn

m = nn.Sigmoid()
print(m(input))
print('-'*100)

target = torch.FloatTensor([[0, 1, 1], [1 , 1, 1], [0, 0, 0]])
print(target)

tensor([[0.8707, 0.7517, 0.8162],
        [0.3411, 0.4872, 0.6815],
        [0.4847, 0.6589, 0.5273]], grad_fn=<SigmoidBackward0>)
----------------------------------------------------------------------------------------------------
tensor([[0., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])


In [7]:
import math

r11 = 0 * math.log(0.8707) + (1 - 0) * math.log((1 - 0.8707))
r12 = 1 * math.log(0.7517) + (1 - 1) * math.log((1 - 0.7517))
r13 = 1 * math.log(0.8162) + (1 - 1) * math.log((1 - 0.8162))

r21 = 1 * math.log(0.3411) + (1 - 1) * math.log((1 - 0.3411))
r22 = 1 * math.log(0.4872) + (1 - 1) * math.log((1 - 0.4872))
r23 = 1 * math.log(0.6815) + (1 - 1) * math.log((1 - 0.6815))

r31 = 0 * math.log(0.4847) + (1 - 0) * math.log((1 - 0.4847))
r32 = 0 * math.log(0.6589) + (1 - 0) * math.log((1 - 0.6589))
r33 = 0 * math.log(0.5273) + (1 - 0) * math.log((1 - 0.5273))

r1 = -(r11 + r12 + r13)/3
r2 = -(r21 + r22 + r23)/3
r3 = -(r31 + r32 + r33)/3

BCELoss = (r1 + r2 + r3)/3

print(BCELoss)



0.8000147727101611


In [8]:
loss = nn.BCELoss()
print(loss(m(input),target))

tensor(0.8000, grad_fn=<BinaryCrossEntropyBackward0>)


In [9]:
loss = nn.BCEWithLogitsLoss() ##内部包含sigmoid
print(loss(input, target))

tensor(0.8000, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
