In [83]:
import torch

需要求导的，可以手动定义

In [84]:
#方法1
x = torch.randn(3,4,requires_grad=True)
x

tensor([[-0.2193, -0.4135, -0.7241, -0.2521],
        [-0.1629, -0.3794,  0.6844, -0.6335],
        [ 1.6184,  3.1404, -0.9005,  0.1610]], requires_grad=True)

In [85]:
#方法2
x = torch.randn(3,4)
x.requires_grad=True
x

tensor([[-0.1501,  0.3372,  0.2179, -0.8315],
        [ 0.2449, -1.3096, -0.0805, -0.3801],
        [ 0.5582,  0.4003, -0.6452,  0.6799]], requires_grad=True)

In [86]:
b = torch.randn(3,4,requires_grad=True)
b

tensor([[-0.7444, -0.7193, -0.5054, -1.8038],
        [ 0.4768,  0.8241,  0.3825, -0.2224],
        [ 1.4408,  0.0320,  0.9040, -1.5608]], requires_grad=True)

In [87]:
t = x + b
t

tensor([[-0.8945, -0.3821, -0.2875, -2.6353],
        [ 0.7217, -0.4855,  0.3020, -0.6025],
        [ 1.9991,  0.4324,  0.2589, -0.8810]], grad_fn=<AddBackward0>)

In [88]:
y = t.sum()
y

tensor(-2.4543, grad_fn=<SumBackward0>)

In [89]:
y.backward()
y.backward()

In [90]:
x.grad

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [91]:
b.grad

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

虽然没有指定t的requires_grad但是需要用到它,也会默认的

In [92]:
x.requires_grad,b.requires_grad,t.requires_grad

(True, True, True)

### 举个例子:

![alt text](pic/backward.drawio.png)

y = w*x
z = y + b
f(x) = w*x + b
模型是一元一次的
初始时我就已经有了一个稳定的输入b
我们每此对这个模型的输入是x
1.5x, 0.8x

In [93]:
#计算流程
x = torch.rand(1)
w = torch.rand(1,requires_grad=True)
b = torch.rand(1,requires_grad=True) 

y=x*w
z=y+b



In [94]:
x.requires_grad,b.requires_grad,w.requires_grad,y.requires_grad,z.requires_grad#注意y也是需要的,因为y是通过w*x得到的结果

(False, True, True, True, True)

In [95]:
x.is_leaf,w.is_leaf,b.is_leaf,y.is_leaf,z.is_leaf

(True, True, True, False, False)

### 反向传播计算

In [96]:
z.backward(retain_graph=True)#如果不清空反向求导的梯度会累加在一起， grad = grad + new_grad 
z.backward()

In [97]:
w.grad

tensor([1.8149])

In [98]:
b.grad##累加在一起

tensor([2.])

In [100]:
x.grad